### ISSUE TITLE
How to search by "string" in the name?

### ISSUE THREAD

**Issue by aborruso** [cocrawler/cdx_toolkit#42]
First of all, thank for this tool!!

I would like to add a filter by filename in this query

```
cdxt --cc --filter '=status:200' iter 'www.interno.gov.it/sites/default/files/*'
```

I would like all pdf files that in the path contain the string "omici" everywhere. 
Is it possible to do this? 

Thanks

**Comment by wumpus** [comment]
The main purpose of the filters is to give you filters that the index server actually uses. There isn't a filter on the name. So in this case, since the number of captures is so small:

```
$ cdxt --cc --filter '=status:200' size 'www.interno.gov.it/sites/default/files/*'
6000
```

I would download the entire results set and then grep it after you have the whole thing.

An alternative is to use the columnar index, and use an SQL query with `WHERE url_path LIKE '%omici%'`

If you want to make a bunch of similar queries, I'd recommend the columnar index over the cdx index.

**Comment by aborruso** [comment]
Thank you very much
